# Generated by Django 4.2.27 on 2026-02-16 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dispatch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='has_dispute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tracking_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered_by_seller', 'Marked Delivered'), ('delivered', 'Delivery Confirmed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered'), ('escalated', 'Escalated'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderItemTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_by_role', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('system', 'System'), ('admin', 'Admin')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='shopping_app.orderitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_item_tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('dispute_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_type', models.CharField(choices=[('not_as_ordered', 'Not the specified item by order'), ('damaged', 'Item is damaged'), ('wrong_details', 'Wrong details/measurements'), ('wrong_quantity', 'Wrong quantity received'), ('inconsistent_payment', 'Inconsistent payment status with delivery'), ('suspicious_seller', 'Suspicious seller/delivery person'), ('counterfeit', 'Suspected counterfeit product'), ('missing_parts', 'Missing parts or accessories'), ('wrong_color_size', 'Wrong color or size'), ('expired_product', 'Product expired or near expiry'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('forwarded_to_payment', 'Forwarded to Payment Platform'), ('under_review', 'Under Review'), ('funds_held', 'Funds Held'), ('refund_approved', 'Refund Approved'), ('refund_processed', 'Refund Processed'), ('resolved_no_refund', 'Resolved — No Refund'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='submitted', max_length=30)),
                ('is_online_payment', models.BooleanField(default=False)),
                ('payment_app_dispute_id', models.IntegerField(blank=True, help_text='Dispute ID in the payment app (Fair Cashier)', null=True)),
                ('payment_app_status', models.CharField(blank=True, help_text='Synced status from payment app', max_length=30, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_disputes_filed', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='shopping_app.order')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='shopping_app.orderitem')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_disputes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_confirmations', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_confirmations', to='shopping_app.order')),
            ],
            options={
                'db_table': 'delivery_confirmations',
                'ordering': ['-created_at'],
            },
        ),
    ]
