# Generated by Django 4.2.27 on 2026-02-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_orderitem_delivery_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdispute',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('escalated', 'Escalated to Admin'), ('resolved_with_refund', 'Resolved With Refund'), ('resolved_without_refund', 'Resolved Without Refund')], default='submitted', max_length=30),
        ),
    ]
