# Generated by Django 4.2.27 on 2026-02-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0004_order_fair_cashier_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_options',
            field=models.JSONField(default=list, help_text="Available payment methods for this item, e.g., ['cash'] or ['cash', 'online']"),
        ),
    ]
