# Generated by Django 4.2.27 on 2026-02-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0005_orderitem_payment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerpayment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sellerpayment',
            name='seller',
        ),
        migrations.DeleteModel(
            name='CashOut',
        ),
        migrations.DeleteModel(
            name='SellerPayment',
        ),
    ]
