# Generated by Django 4.2.27 on 2026-03-01 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shopping_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0006_alter_orderitem_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_legal_name', models.CharField(max_length=255)),
                ('national_id_number', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=30)),
                ('physical_address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('country', models.CharField(default='Uganda', max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('business_registration_no', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(choices=[('individual', 'Individual / Sole Trader'), ('partnership', 'Partnership'), ('company', 'Registered Company'), ('ngo', 'NGO / Non-profit')], default='individual', max_length=50)),
                ('business_address', models.TextField(blank=True)),
                ('tin_number', models.CharField(blank=True, max_length=100, verbose_name='TIN Number')),
                ('national_id_front', models.FileField(upload_to=shopping_app.models.seller_doc_upload_path)),
                ('national_id_back', models.FileField(blank=True, null=True, upload_to=shopping_app.models.seller_doc_upload_path)),
                ('selfie_with_id', models.FileField(blank=True, null=True, upload_to=shopping_app.models.seller_doc_upload_path)),
                ('business_cert', models.FileField(blank=True, null=True, upload_to=shopping_app.models.seller_doc_upload_path, verbose_name='Business Registration Certificate')),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to=shopping_app.models.seller_doc_upload_path)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='incomplete', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('zkp_status', models.CharField(choices=[('not_registered', 'Not Registered'), ('registered', 'Registered in Merkle Tree'), ('failed', 'Registration Failed')], db_index=True, default='not_registered', max_length=20)),
                ('zkp_commitment_hash', models.CharField(blank=True, help_text='Merkle leaf commitment returned by Strapi ZKP', max_length=512)),
                ('zkp_merkle_root', models.CharField(blank=True, max_length=512)),
                ('zkp_registered_at', models.DateTimeField(blank=True, null=True)),
                ('zkp_last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('zkp_proof_cached', models.JSONField(blank=True, help_text='Latest cached proof object from Strapi', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('seller', models.OneToOneField(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller KYC Verification',
                'verbose_name_plural': 'Seller KYC Verifications',
                'db_table': 'seller_kyc_verifications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
