# Generated by Django 4.2.27 on 2026-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0007_sellerverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerverification',
            name='zkp_block_number',
            field=models.IntegerField(blank=True, help_text='Block number at time of Merkle tree registration', null=True),
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='zkp_leaf_index',
            field=models.IntegerField(blank=True, help_text='Leaf index in the Merkle tree (from Strapi registration)', null=True),
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='zkp_public_signals',
            field=models.JSONField(blank=True, help_text='Public signals from PLONK KYC proof generation', null=True),
        ),
        migrations.CreateModel(
            name='BalanceProofVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, help_text='Matches Order.order_number', max_length=50)),
                ('seller_email', models.EmailField(db_index=True, max_length=254)),
                ('tier_result', models.CharField(choices=[('green', 'Green — buyer can pay all items'), ('amber', 'Amber — buyer can pay some items'), ('red', 'Red — buyer cannot pay any items'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('items_payable', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('binary_bracket', models.IntegerField(default=0, help_text='Power-of-two bracket from proof')),
                ('verified', models.BooleanField(default=False, help_text='True if Strapi confirmed proof valid')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('proof', models.JSONField(blank=True, help_text='Groth16 proof for re-verification', null=True)),
                ('public_signals', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'balance_proof_verifications',
                'ordering': ['-created_at'],
                'unique_together': {('order_number', 'seller_email')},
            },
        ),
    ]
