# Generated by Django 4.2.27 on 2026-03-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0008_sellerverification_zkp_block_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceproofverification',
            name='item_details',
            field=models.JSONField(blank=True, help_text='Per-item payability from Payment App: [{shopping_order_item_id, amount, payable}]', null=True),
        ),
    ]
