# Generated by Django 4.2.27 on 2026-03-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0009_balanceproofverification_item_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdispute',
            name='complaint_type',
            field=models.CharField(choices=[('not_as_ordered', 'Not the specified item by order'), ('damaged', 'Item is damaged'), ('wrong_details', 'Wrong details/measurements'), ('wrong_quantity', 'Wrong quantity received'), ('inconsistent_payment', 'Inconsistent payment status with delivery'), ('suspicious_seller', 'Suspicious seller/delivery person'), ('counterfeit', 'Suspected counterfeit product'), ('missing_parts', 'Missing parts or accessories'), ('wrong_color_size', 'Wrong color or size'), ('expired_product', 'Product expired or near expiry'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderdispute',
            name='payment_app_status',
            field=models.CharField(blank=True, help_text='Synced status from payment app', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderdispute',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('escalated', 'Escalated to Admin'), ('resolved_with_refund', 'Resolved With Refund'), ('resolved_without_refund', 'Resolved Without Refund')], default='submitted', max_length=50),
        ),
    ]
