# Generated by Django 4.2.27 on 2026-03-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0010_alter_orderdispute_complaint_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtracking',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
