# Generated by Django 4.2.27 on 2026-03-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0011_alter_orderitemtracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='online_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial'), ('escrowed', 'Escrowed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('deposited', 'Payment Reseved'), ('escrowed', 'Escrowed')], default='pending', max_length=20),
        ),
    ]
