"""
Shopping App — views_balance_proof.py (NEW)

Verifies buyer balance proofs generated by the Payment App.
Uses: Order, OrderItem, BalanceProofVerification models.

Shopping App NEVER sees the buyer's actual wallet balance.
"""

import json
import logging
import requests as http_requests

from django.conf import settings
from django.http import JsonResponse
from django.utils import timezone
from django.utils.dateparse import parse_datetime
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods

from .models import Order, OrderItem
from .zkp_client import ZKPClient

logger = logging.getLogger(__name__)

try:
    from .models import BalanceProofVerification
except ImportError:
    BalanceProofVerification = None
    logger.warning("BalanceProofVerification model not found — run migrations")


def _payment_url():
    return getattr(settings, 'PAYMENT_APP_URL', 'http://localhost:8001')

def _secret():
    return getattr(settings, 'SHOPPING_APP_INTERNAL_SECRET', '')


# ─── Called from process_payment_selection() after order creation ───

def request_balance_proofs_for_order(order):
    """
    Call Payment App to generate balance proofs for a new order.
    Call this after Order + OrderItems are saved.
    Returns dict with proofs or None on failure.
    """
    buyer_email = order.buyer.email

    sellers_map = {}
    for item in order.items.select_related('seller').all():
        se = item.seller.email
        if se not in sellers_map:
            sellers_map[se] = []
        sellers_map[se].append({
            'shopping_order_item_id': item.id,
            'amount': float(item.subtotal),
            'payment_method': item.payment_method,
        })

    if not sellers_map:
        return None

    sellers_payload = [{'seller_email': e, 'items': items} for e, items in sellers_map.items()]

    try:
        resp = http_requests.post(
            f"{_payment_url()}/internal/order-created/",
            json={'order_id': order.order_number, 'buyer_email': buyer_email, 'sellers': sellers_payload},
            headers={'X-Internal-Secret': _secret(), 'Content-Type': 'application/json'},
            timeout=60,
        )
        if resp.status_code != 200:
            logger.error(f"Payment App returned {resp.status_code}: {resp.text[:300]}")
            return None
        data = resp.json()
    except http_requests.exceptions.RequestException as e:
        logger.error(f"Balance proof request failed: {e}")
        return None

    zkp = ZKPClient()
    verified_proofs = []

    for pd in data.get('proofs', []):
        proof = pd.get('proof')
        pub = pd.get('public_signals')
        se = pd.get('seller_email', '')
        ok = False

        if proof and pub:
            try:
                ok = zkp.verify_balance_proof(proof, pub).get('verified', False)
            except Exception as e:
                logger.error(f"Balance verify failed for {se}: {e}")

        verified_proofs.append({
            'seller_email': se, 'tier_result': pd.get('tier_result', 'unknown'),
            'items_payable': pd.get('items_payable', 0), 'total_items': pd.get('total_items', 0),
            'verified': ok,
        })

        _store(order.order_number, se, pd.get('tier_result', 'unknown'),
               pd.get('items_payable', 0), pd.get('total_items', 0),
               pd.get('binary_bracket', 0), ok, proof, pub, pd.get('expires_at'))

    logger.info(f"Balance proofs for {order.order_number}: {sum(1 for p in verified_proofs if p['verified'])}/{len(verified_proofs)} verified")
    return {'order_id': order.order_number, 'proofs': verified_proofs}


# ─── Seller-triggered refresh ───

def refresh_balance_proof_for_seller(order, seller_email, include_cod=False):
    items = [{'shopping_order_item_id': i.id, 'amount': float(i.subtotal), 'payment_method': i.payment_method}
             for i in order.items.filter(seller__email=seller_email)]
    if not items:
        return None

    try:
        resp = http_requests.post(
            f"{_payment_url()}/internal/balance-proof/refresh/",
            json={'order_id': order.order_number, 'seller_email': seller_email, 'include_cod': include_cod, 'items': items},
            headers={'X-Internal-Secret': _secret(), 'Content-Type': 'application/json'},
            timeout=60,
        )
        if resp.status_code != 200:
            return None
        data = resp.json()
    except http_requests.exceptions.RequestException as e:
        logger.error(f"Refresh failed: {e}")
        return None

    proof, pub = data.get('proof'), data.get('public_signals')
    ok = False
    if proof and pub:
        try:
            ok = ZKPClient().verify_balance_proof(proof, pub).get('verified', False)
        except Exception:
            pass

    _store(order.order_number, seller_email, data.get('tier_result', 'unknown'),
           data.get('items_payable', 0), data.get('total_items', 0),
           data.get('binary_bracket', 0), ok, proof, pub, data.get('expires_at'), is_refresh=True)

    return {'order_id': order.order_number, 'seller_email': seller_email,
            'tier_result': data.get('tier_result', 'unknown'),
            'items_payable': data.get('items_payable', 0),
            'total_items': data.get('total_items', 0), 'verified': ok,
            'refreshed_at': data.get('refreshed_at'), 'include_cod': include_cod}


# ─── Storage ───

def _store(order_number, seller_email, tier, payable, total, bracket, verified,
           proof=None, pub=None, expires_at=None, is_refresh=False):
    if not BalanceProofVerification:
        return
    expires_dt = parse_datetime(expires_at) if isinstance(expires_at, str) else expires_at
    try:
        obj, _ = BalanceProofVerification.objects.update_or_create(
            order_number=order_number, seller_email=seller_email,
            defaults={'tier_result': tier, 'items_payable': payable, 'total_items': total,
                      'binary_bracket': bracket, 'verified': verified, 'proof': proof,
                      'public_signals': pub, 'verified_at': timezone.now() if verified else None,
                      'expires_at': expires_dt})
        if is_refresh:
            obj.refresh_count = (obj.refresh_count or 0) + 1
            obj.save(update_fields=['refresh_count'])
    except Exception as e:
        logger.error(f"Store failed: {e}")

def _get_stored(order_number, seller_email):
    if not BalanceProofVerification:
        return None
    try:
        v = BalanceProofVerification.objects.get(order_number=order_number, seller_email=seller_email)
        return {'tier_result': v.tier_result, 'items_payable': v.items_payable,
                'total_items': v.total_items, 'verified': v.verified,
                'verified_at': v.verified_at.isoformat() if v.verified_at else None,
                'is_expired': v.is_expired, 'refresh_count': v.refresh_count}
    except BalanceProofVerification.DoesNotExist:
        return None


# ─── API Views ───

@csrf_exempt
@require_http_methods(["GET"])
def order_balance_status(request, order_id):
    """GET /order/<order_id>/balance-status/?seller_email=X"""
    se = request.GET.get('seller_email', '').strip().lower()
    if not se:
        return JsonResponse({'error': 'seller_email required'}, status=400)

    try:
        Order.objects.get(order_number=order_id)
    except Order.DoesNotExist:
        return JsonResponse({'error': 'Order not found'}, status=404)

    local = _get_stored(order_id, se)
    if local:
        return JsonResponse({'order_id': order_id, 'seller_email': se, **local})

    try:
        resp = http_requests.get(
            f"{_payment_url()}/internal/balance-proof/?order_id={order_id}&seller_email={se}",
            headers={'X-Internal-Secret': _secret()}, timeout=15)
        if resp.status_code == 200:
            d = resp.json()
            return JsonResponse({'order_id': order_id, 'seller_email': se,
                                 'tier_result': d.get('tier_result', 'unknown'),
                                 'items_payable': d.get('items_payable', 0),
                                 'total_items': d.get('total_items', 0),
                                 'verified': False, 'is_expired': d.get('is_expired', False)})
    except Exception as e:
        logger.error(f"Fetch failed: {e}")

    return JsonResponse({'order_id': order_id, 'seller_email': se,
                         'tier_result': 'unknown', 'verified': False}, status=404)


@csrf_exempt
@require_http_methods(["POST"])
def refresh_balance_status(request, order_id):
    """POST /order/<order_id>/balance-refresh/ {seller_email, include_cod}"""
    body = json.loads(request.body)
    se = body.get('seller_email', '').strip().lower()
    include_cod = body.get('include_cod', False)
    if not se:
        return JsonResponse({'error': 'seller_email required'}, status=400)

    try:
        order = Order.objects.get(order_number=order_id)
    except Order.DoesNotExist:
        return JsonResponse({'error': 'Order not found'}, status=404)

    if not order.items.filter(seller__email=se).exists():
        return JsonResponse({'error': 'Seller has no items in this order'}, status=400)

    result = refresh_balance_proof_for_seller(order, se, include_cod)
    return JsonResponse(result) if result else JsonResponse({'error': 'Refresh failed'}, status=502)